# Generated by Django 3.1.3 on 2020-11-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201108_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-time_created']},
        ),
    ]
