# Generated by Django 3.1.3 on 2020-11-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
