# Generated by Django 3.1.3 on 2020-11-08 23:23

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('brand', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
