# Generated by Django 3.1.3 on 2020-11-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
