# Generated by Django 3.1.3 on 2020-11-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201111_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
